import { Hand, PositionStat, Stats } from "./types";

export const sampleHands: Hand[] = [
  { id:"PC-28419", playedAt:"2026-07-18 22:41", game:"NL Hold’em", stakes:"¥50 / ¥100", hero:"Hero", position:"BTN", holeCards:["A♠","8♠"], board:["K♠","7♦","2♣","J♠","4♥"], pot:2450, result:-800, actualAction:"Call", recommendation:{fold:68,call:18,raise:14}, score:42, issue:"プリフロップのコールドコール", explanation:"BTNでも、HJのオープンに対するA8sは相手のレンジ次第でフォールドが中心です。コールするとドミネートされやすく、フロップ以降も難しい判断が増えます。", actions:[{street:"preflop",player:"HJ",type:"raise",amount:250},{street:"preflop",player:"Hero",type:"call",amount:250},{street:"preflop",player:"BB",type:"call",amount:150},{street:"flop",player:"BB",type:"check"},{street:"flop",player:"HJ",type:"bet",amount:420},{street:"flop",player:"Hero",type:"call",amount:420},{street:"turn",player:"HJ",type:"bet",amount:800},{street:"turn",player:"Hero",type:"fold"}]},
  { id:"PC-28388", playedAt:"2026-07-18 22:08", game:"NL Hold’em", stakes:"¥50 / ¥100", hero:"Hero", position:"BB", holeCards:["Q♥","J♣"], board:["Q♣","8♠","5♦","3♣","A♦"], pot:3900, result:-1750, actualAction:"Raise", recommendation:{fold:8,call:76,raise:16}, score:51, issue:"トップペアの過剰なレイズ", explanation:"このボードでは弱いハンドを降ろし、強いハンドだけにコールされやすいレイズです。コールで相手のブラフを残し、ターンを評価する方が期待値を保ちやすくなります。", actions:[{street:"preflop",player:"CO",type:"raise",amount:250},{street:"preflop",player:"Hero",type:"call",amount:150},{street:"flop",player:"Hero",type:"check"},{street:"flop",player:"CO",type:"bet",amount:330},{street:"flop",player:"Hero",type:"raise",amount:1050},{street:"flop",player:"CO",type:"call",amount:720},{street:"turn",player:"Hero",type:"bet",amount:1450},{street:"turn",player:"CO",type:"raise",amount:3200},{street:"turn",player:"Hero",type:"fold"}]},
  { id:"PC-28351", playedAt:"2026-07-18 21:26", game:"NL Hold’em", stakes:"¥50 / ¥100", hero:"Hero", position:"CO", holeCards:["9♣","9♦"], board:["9♥","6♠","2♠","K♣","6♦"], pot:8620, result:4310, actualAction:"Raise", recommendation:{fold:3,call:7,raise:90}, score:96, actions:[{street:"preflop",player:"Hero",type:"raise",amount:250},{street:"preflop",player:"BTN",type:"call",amount:250},{street:"flop",player:"Hero",type:"bet",amount:340},{street:"flop",player:"BTN",type:"call",amount:340},{street:"turn",player:"Hero",type:"bet",amount:900},{street:"turn",player:"BTN",type:"call",amount:900},{street:"river",player:"Hero",type:"bet",amount:2820},{street:"river",player:"BTN",type:"call",amount:2820}]},
  { id:"PC-28317", playedAt:"2026-07-18 21:04", game:"NL Hold’em", stakes:"¥50 / ¥100", hero:"Hero", position:"BB", holeCards:["A♦","Q♣"], board:["8♣","5♦","2♠","K♥","3♣"], pot:1720, result:860, actualAction:"Raise", recommendation:{fold:1,call:4,raise:95}, score:98, explanation:"BTNの広いオープンに対してAQoをBBから3BET。ハンドの強さとポジション関係に合った、期待値の高い判断です。", actions:[{street:"preflop",player:"BTN",type:"raise",amount:250},{street:"preflop",player:"Hero",type:"raise",amount:950},{street:"preflop",player:"BTN",type:"call",amount:700},{street:"flop",player:"Hero",type:"bet",amount:480},{street:"flop",player:"BTN",type:"fold"}]},
  { id:"PC-28290", playedAt:"2026-07-18 20:37", game:"NL Hold’em", stakes:"¥50 / ¥100", hero:"Hero", position:"SB", holeCards:["K♦","7♦"], board:["T♣","7♠","4♥"], pot:1100, result:-550, actualAction:"Call", recommendation:{fold:82,call:12,raise:6}, score:34, issue:"SBからの広すぎる参加", explanation:"SBはポストフロップで常に不利な位置になります。K7sは見た目以上に実現エクイティが低いため、BTNオープンに対してはフォールド頻度を上げましょう。", actions:[{street:"preflop",player:"BTN",type:"raise",amount:250},{street:"preflop",player:"Hero",type:"call",amount:200},{street:"flop",player:"Hero",type:"check"},{street:"flop",player:"BTN",type:"bet",amount:300},{street:"flop",player:"Hero",type:"call",amount:300},{street:"turn",player:"Hero",type:"fold"}]},
];
export const sampleStats: Stats = { hands:1248, vpip:27.4, pfr:18.1, threeBet:6.2, cbet:71.3, cbetOpportunities:216, foldToCbet:54.8, foldToCbetOpportunities:188, net:1860, netBb:18.6, winRateBb100:1.5, averageScore:86.2 };
export const positionStats: PositionStat[] = [
  {position:"UTG",hands:201,bb100:4.2,vpip:17,pfr:15},{position:"HJ",hands:198,bb100:7.8,vpip:21,pfr:18},{position:"CO",hands:213,bb100:13.4,vpip:29,pfr:24},{position:"BTN",hands:207,bb100:21.8,vpip:43,pfr:33},{position:"SB",hands:205,bb100:-18.2,vpip:35,pfr:20},{position:"BB",hands:224,bb100:-32.4,vpip:38,pfr:12},
];
