"use client";
import { useState } from "react";
import Link from "next/link";
import { TrendingUp, TrendingDown, ChevronRight } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ReferenceArea, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { usePoker } from "@/components/poker-provider";
import { calculatePositions, calculateStats } from "@/lib/analyzer";
import { positionStats as samples, sampleStats } from "@/lib/sample-data";

type MetricKey="VPIP"|"PFR"|"3BET"|"CBET"|"FOLD TO CBET";
const configs:{key:MetricKey;field:"vpip"|"pfr"|"threeBet"|"cbet"|"foldToCbet";label:string;range:[number,number];color:string}[]=[
 {key:"VPIP",field:"vpip",label:"参加率",range:[20,28],color:"#1e6656"},{key:"PFR",field:"pfr",label:"プリフロップレイズ",range:[16,23],color:"#287c68"},{key:"3BET",field:"threeBet",label:"リレイズ率",range:[6,10],color:"#b08132"},{key:"CBET",field:"cbet",label:"継続ベット",range:[55,70],color:"#cf714d"},{key:"FOLD TO CBET",field:"foldToCbet",label:"CBETに降りた率",range:[40,55],color:"#7e6b9e"}
];

export default function Dashboard(){
 const {hands}=usePoker(); const imported=hands.length>0; const stats=imported?calculateStats(hands):sampleStats; const positions=imported?calculatePositions(hands):samples;
 const [selected,setSelected]=useState<MetricKey>("VPIP"); const active=configs.find(c=>c.key===selected)!;
 const trend=hands.map((_,i)=>{const s=calculateStats(hands.slice(0,i+1));return {hand:i+1,VPIP:s.vpip,PFR:s.pfr,"3BET":s.threeBet,CBET:s.cbetOpportunities?s.cbet:null,"FOLD TO CBET":s.foldToCbetOpportunities?s.foldToCbet:null}});
 const activeOpportunities=active.field==="cbet"?stats.cbetOpportunities:active.field==="foldToCbet"?stats.foldToCbetOpportunities:null;
 return <main>
  <div className="page-heading compact"><div><span className="eyebrow">SESSION OVERVIEW</span><h1>統計ダッシュボード</h1><p>{stats.hands.toLocaleString()}ハンドから見えた、あなたのプレイ傾向</p></div><div className="session-pill">直近のセッション⌄</div></div>
  <section className="summary-strip"><div><small>総ハンド</small><strong>{stats.hands.toLocaleString()}</strong></div><div><small>収支</small><strong className={stats.net>=0?"positive":"negative"}>{stats.net>=0?"+":""}{stats.net.toLocaleString()} BB</strong></div><div><small>WIN RATE</small><strong>+1.49 <em>BB/100</em></strong></div><div className="grade"><small>SESSION GRADE</small><strong>B<span>+</span></strong></div></section>
  <div className="metric-grid">{configs.map((m,i)=>{const value=stats[m.field],opportunities=m.field==="cbet"?stats.cbetOpportunities:m.field==="foldToCbet"?stats.foldToCbetOpportunities:null,hasData=opportunities===null||opportunities>0;return <article role="button" tabIndex={0} aria-pressed={selected===m.key} onClick={()=>setSelected(m.key)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")setSelected(m.key)}} className={selected===m.key?"metric-card selected":"metric-card"} key={m.key} style={{"--metric-color":m.color} as React.CSSProperties}><div><span>{m.key}</span>{i<2?<TrendingUp className="up" size={17}/>:i===3?<TrendingDown className="down" size={17}/>:null}</div><strong>{hasData?value:"—"}{hasData&&<em>%</em>}</strong><small>{hasData?m.label:"対象機会なし"}</small><div className="meter"><i style={{width:`${hasData?Math.min(Number(value),100):0}%`}}/></div><footer>{opportunities!==null?`対象 ${opportunities}回・`:null}目安 {m.range[0]}–{m.range[1]}%</footer><span className="tap-hint">タップして推移を見る</span></article>})}</div>
  <section className="trend-card"><div className="trend-heading"><div><span className="eyebrow">TREND BY HANDS</span><h2>{selected}の推移</h2><p>{activeOpportunities===0?"このセッションには集計対象となる場面がありません":activeOpportunities!==null?`対象 ${activeOpportunities}回の累積値`:"各ハンド終了時点の累積値"}</p></div><div className="trend-current"><small>CURRENT</small><strong style={{color:active.color}}>{activeOpportunities===0?"—":`${stats[active.field]}%`}</strong></div></div><div className="trend-chart"><ResponsiveContainer width="100%" height={270}><LineChart data={trend} margin={{top:16,right:18,left:-15,bottom:5}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e7e3da"/><ReferenceArea y1={active.range[0]} y2={active.range[1]} fill={active.color} fillOpacity={.08}/><XAxis dataKey="hand" axisLine={false} tickLine={false} label={{value:"総ハンド数",position:"insideBottomRight",offset:-4,fontSize:9}}/><YAxis domain={[0,100]} axisLine={false} tickLine={false} unit="%"/><Tooltip formatter={(v)=>[`${v}%`,selected]} labelFormatter={v=>`${v}ハンド終了時`}/><Line connectNulls={false} type="monotone" dataKey={selected} stroke={active.color} strokeWidth={3} dot={{r:3,fill:active.color,strokeWidth:0}} activeDot={{r:6}} animationDuration={300}/></LineChart></ResponsiveContainer></div><div className="range-key"><i style={{background:active.color}}/>薄い帯は目安範囲 {active.range[0]}–{active.range[1]}%</div></section>
  <section className="chart-card"><div className="section-title"><div><span className="eyebrow">BY POSITION</span><h2>ポジション別パフォーマンス</h2></div><div className="legend"><i/> BB / 100</div></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={250}><BarChart data={positions} margin={{top:10,right:10,left:-20,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e7e3da"/><XAxis dataKey="position" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip cursor={{fill:"#f5f2ea"}}/><Bar dataKey="bb100" fill="#1e6656" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div><div className="position-table"><div className="table-head"><span>POSITION</span><span>HANDS</span><span>VPIP</span><span>PFR</span><span>BB/100</span></div>{positions.map(p=><div className="table-row" key={p.position}><b>{p.position}</b><span>{p.hands}</span><span>{p.vpip}%</span><span>{p.pfr}%</span><strong className={p.bb100>=0?"positive":"negative"}>{p.bb100>0?"+":""}{p.bb100}</strong></div>)}</div></section>
  <Link className="insight-banner" href="/improvements"><span className="insight-icon">!</span><div><b>{hands.filter(h=>h.issue).length}件の改善ポイントが見つかりました</b><small>判断スコアの低いハンドから確認しましょう</small></div><span>改善ハンドを見る <ChevronRight size={18}/></span></Link>
  <style jsx global>{`
   .metric-card{cursor:pointer;position:relative;transition:.18s;outline:none}.metric-card:hover{transform:translateY(-2px);box-shadow:0 8px 20px #273c3511}.metric-card.selected{border:2px solid var(--metric-color);padding:16px;background:#fff}.metric-card.selected .meter i{background:var(--metric-color)}.tap-hint{display:block;font-size:8px;color:var(--metric-color);margin-top:9px;opacity:0}.metric-card:hover .tap-hint,.metric-card.selected .tap-hint{opacity:1}.trend-card{background:var(--paper);border:1px solid var(--line);border-radius:14px;padding:24px;margin-bottom:22px;box-shadow:0 10px 30px rgba(38,53,47,.035)}.trend-heading{display:flex;justify-content:space-between;align-items:end}.trend-heading h2{font-size:21px;margin:7px 0 5px}.trend-heading p{font-size:10px;color:#8a918d;margin:0}.trend-current{text-align:right}.trend-current small{font-size:8px;color:#9ba09d;display:block}.trend-current strong{font-size:25px}.trend-chart{height:270px;margin-top:9px}.range-key{font-size:9px;color:#858c88;display:flex;align-items:center;gap:6px}.range-key i{width:13px;height:7px;border-radius:2px;opacity:.3}@media(max-width:600px){.metric-grid{display:flex;overflow-x:auto;padding-bottom:8px;scroll-snap-type:x mandatory}.metric-card{min-width:155px;scroll-snap-align:start}.trend-card{padding:16px}.trend-current strong{font-size:20px}}
  `}</style>
 </main>
}
